### ISSUE TITLE
Refactor ClassVoxel Management

### ISSUE THREAD

**Issue by renezurbruegg** [ethz-asl/panoptic_mapping#29]
Refactor the current ClassVoxel implementation with member methods of specific voxels. 
Additionally 
- Move VoxelAccuracy to ClassVoxelLayer and provide getVoxelUncertainty() in layer
- Move Uncertainty Decay Rate to Parameters.

Not specific to your code, but more of a general design consideration: Changing all these functions to members of the specific voxels and writing a wrapper of the ClassVoxelLayer might be a cleaner solution?

_Originally posted by @Schmluk in https://github.com/ethz-asl/panoptic_mapping/pull/19#r721457508_

These feel like they should be parameters (of the integrator or similar). Avoid using pre-compiler macros where possible.

_Originally posted by @Schmluk in https://github.com/ethz-asl/panoptic_mapping/pull/19#discussion_r721438794_

**Comment by Schmluk** [comment]
Class voxel abstraction implemented in #37 :)
