### ISSUE TITLE
 proto import compilation error

### ISSUE THREAD

**Issue by marcokat81** [ethz-asl/panoptic_mapping#50]
Hi @Schmluk 
I am using ubuntu 18.04 + melodic environment. I am unable to compile the panoptic_mapping package due to the following error. 

```
cblox/QuatTransformation.proto: File not found.
panoptic_mapping/Submap.proto: Import "cblox/QuatTransformation.proto" was not found or had errors.
panoptic_mapping/Submap.proto:26:12: "cblox.QuatTransformationProto" is not defined.
make[2]: *** [compiled_proto/panoptic_mapping/Submap.pb.cc] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/panoptic_mapping_proto.dir/all] Error 2
make: *** [all] Error 2
```
However I can successfully compile the `cblox` package 

It looks like the panoptic mapping package is not able to locate the QuatTransformation.proto files. Any idea why this would happen ? What would you suggest I do to resolve this ?

**Comment by Schmluk** [comment]
Hi @marcokat81 

As long as everything is in the same catkin workspace this should work. Did you source your catkin workspace?

**Comment by marcokat81** [comment]
Hi @Schmluk  .... it looks to happen when my workspace is not set to `catkin config --merge-devel` .

**Comment by marcokat81** [comment]
@Schmluk  .... Is there a parameter which will enable us to semantically control the temporal decay rate for the mesh generation ? like slowly decay the maps for specific class and rapid decay rates for some others. 

I experimented with max_weight param inside the tsdf_integrator  I had to drastically lower it down to 100 to get faster decay rate. is it possible to control this semantically ?  I noticed that mesh of smaller objects with less pixel coverage in the input image are rapidly eaten up by the mesh of its surrounding semantic class ? do we have the ability to custom control this behavior ? like providing ground truth for specific semantic classes so it stays within the map for longer period ?  

`weight_dropoff_epsilon` did not seem to do anything  I did not understand how that is used ?

**Comment by Schmluk** [comment]
Hi @marcokat81 

Great to hear that it worked! Can you please open a new issue for new requests and close this one if your issue has been addressed? Then other users can also find answers to the their questions. Thanks!
