### ISSUE TITLE
 Semantic Temporal Decay rate 

### ISSUE THREAD

**Issue by marcokat81** [ethz-asl/panoptic_mapping#51]
Hit @Schmluk .... Is there a parameter which will enable us to semantically control the temporal decay rate for the mesh generation ? like slowly decay the maps for specific class and rapid decay rates for some others.

I experimented with max_weight param inside the tsdf_integrator I had to drastically lower it down to 100 to get faster decay rate. is it possible to control this semantically ? I noticed that mesh of smaller objects with less pixel coverage in the input image are rapidly eaten up by the mesh of its surrounding semantic class ? is it possible to custom control this behavior ? like providing ground truth segmentation for specific semantic classes so it stays within the map for longer period and providing higher uncertainty to other segmentation classes ?

weight_dropoff_epsilon did not seem to do anything I did not understand how that is used ?

**Comment by Schmluk** [comment]
Hi @marcokat81 

There is currently no parameter for that but it is easily addable. During the map update (in the ClassTsdfIntegartor) for every voxel also the corresponding class voxel is found. You can use that information to change the update rule or update weights. 

Are your questions for the single or multi TSDF case? In the latter, it could be that small objects are mostly harder to detect and therefore their probabilities are decreased.

weight_dropoff_epsilon was introduced in [voxblox](https://github.com/ethz-asl/voxblox), it reduces the weight for the part of the TSDF that is inside the object.

Hope this helps!

**Comment by marcokat81** [comment]
@Schmluk  where is the corresponding voxel found ? is it [this](https://github.com/ethz-asl/panoptic_mapping/blob/main/panoptic_mapping/src/integration/class_projective_tsdf_integrator.cpp#L117)  

My question is regarding the Multi-TSDF case. Yes Some smaller objects like poles are harder to semantically detect but I still see some pixels show up   .... I decreased the min_allocation_size on the id_tracker so that they are always considered as well ... 

may be we can have a higher prior for detections for certain class probabilities ? where are the class probabilities calculated ?

**Comment by Schmluk** [comment]
Yes that is it. Notice that `class_voxel` can be nullptr if no class voxel exists there.

The class probabilities are estimated by the network. They are fused in the ClassProjectiveIntegrator [L152](https://github.com/ethz-asl/panoptic_mapping/blob/main/panoptic_mapping/src/integration/class_projective_tsdf_integrator.cpp#L152).

Thin objects are generally hard to reconstruct, this is an inherent limitation of TSDFs. Yes, the same logic as above can also be used in the single TSDF case.

**Comment by marcokat81** [comment]
@Schmluk  which network are you referring to ? are you talking about the segmentation model network ?

**Comment by Schmluk** [comment]
Closed due to inactivity.
