### ISSUE TITLE
[flat_data_player-1] process has died

### ISSUE THREAD

**Issue by xfDing815** [ethz-asl/panoptic_mapping#70]
hello!When I run the code 
 **roslaunch panoptic_mapping_ros run.launch** 
An error occurred:
![ZO0JC_X}@FDL~SE6M0W9NAT](https://github.com/ethz-asl/panoptic_mapping/assets/115251393/222b2ac4-bc9b-4a21-8d82-03dd2723c818)
Do you know how to deal with it?
Thanks!!

**Comment by Schmluk** [comment]
Hi @xfDing815 

Thank you for your patience! This looks like the player can not find some files of the dataset. Can you also print the errors of the player (by setting `output="screen"` in the node in the launch file), check that all files re found, and otherwise show the errors?

Hope that helps!

**Comment by magistri** [comment]
Hi,

I have the same issue. I'd guess that the bag file is not included in flat_dataset.zip that is being downloaded with the script

**Comment by Schmluk** [comment]
The dataset is organized as images, poses and time stamps file. The flat data player reads these files and publishes them as ROS messages. Can you double check that the data is being extracted from the .zip and the data player reads the correct path?

**Comment by Schmluk** [comment]
Closed due to inactivity.
