### ISSUE TITLE
Cannot download the flat_dataset

### ISSUE THREAD

**Issue by anranli2003** [ethz-asl/panoptic_mapping#72]
Hey, I was trying to run the demo flat_dataset, however the provided link on the website (https://projects.asl.ethz.ch/datasets/doku.php?id=panoptic_mapping) isn't working. Is there another way we could download it?
Thanks

**Comment by Schmluk** [comment]
Hi @anranli2003 ,

I just tested the website and on my side it seems to be working. What error are you getting?

**Comment by anranli2003** [comment]
Sorry I should've been more clear. I can open the website, but the download flat_dataset link at the bottom of the page isn't working. When I click on it, it would flash and nothing downloads. I've also tried on other laptops and computers with no success.

(nvm, I was able to resolve this by copying the url from "open link in new tab" and use wget in the terminal)
